// Mocks generated by Mockito 5.2.0 from annotations
// in app_cats/test/features/cat_detail/domain/usecases/get_cats_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:app_cats/core/error/failures.dart' as _i5;
import 'package:app_cats/features/cat_detail/domain/entities/cat.dart' as _i6;
import 'package:app_cats/features/cat_detail/domain/repositories/cat_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [CatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatRepository extends _i1.Mock implements _i3.CatRepository {
  MockCatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Cat>>> getCats() =>
      (super.noSuchMethod(Invocation.method(#getCats, []),
              returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Cat>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Cat>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Cat>>>);
}
