// Mocks generated by Mockito 5.2.0 from annotations
// in app_cats/test/features/cat_detail/data/repositories/cat_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:app_cats/core/network/network_info.dart' as _i6;
import 'package:app_cats/features/cat_detail/data/datasources/cat_local_data_source.dart'
    as _i5;
import 'package:app_cats/features/cat_detail/data/datasources/cat_remote_data_source.dart'
    as _i2;
import 'package:app_cats/features/cat_detail/data/models/cat_dto.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [CatRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatRemoteDataSource extends _i1.Mock
    implements _i2.CatRemoteDataSource {
  MockCatRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CatDTO>> getCats() =>
      (super.noSuchMethod(Invocation.method(#getCats, []),
              returnValue: Future<List<_i4.CatDTO>>.value(<_i4.CatDTO>[]))
          as _i3.Future<List<_i4.CatDTO>>);
}

/// A class which mocks [CatLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatLocalDataSource extends _i1.Mock
    implements _i5.CatLocalDataSource {
  MockCatLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CatDTO>> getCats() =>
      (super.noSuchMethod(Invocation.method(#getCats, []),
              returnValue: Future<List<_i4.CatDTO>>.value(<_i4.CatDTO>[]))
          as _i3.Future<List<_i4.CatDTO>>);
  @override
  _i3.Future<void> cacheCats(List<_i4.CatDTO>? cats) =>
      (super.noSuchMethod(Invocation.method(#cacheCats, [cats]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
}
